config/routes.rb
Rails.application.routes.draw do
  resources :messages
   resources :project_threads
   resources :attachments
   resources :users do
     resources :projects
     get 'logout', :on => :collection
     get 'login', :on => :collection
     post 'login' => 'users#submit_login', :on => :collection
     get 'dashboard', :on => :collection
     get 'profile', :on => :collection
     patch 'profile' => 'users#submit_profile', :on => :collection
     get 'projects', :on => :collection
     get 'projects/shared' => "users#shared_projects", :on => :collection
     get 'projects/create' => 'users#create_project', :on => :collection
     post 'projects/create' => 'projects#create', :on => :collection
     get 'projects/view/:projectid' => 'projects#show', :on => :collection
     get 'projects/edit/:projectid' => 'users#edit_project', :on => :collection
     post 'projects/edit/:projectid' => 'projects#update', :on => :collection
     get 'projects/delete/:projectid' => 'projects#destroy', :on => :collection
     get 'projects/:projectid/attachments/delete/:id' => 'projects#delete_attachment', :on => :collection
     get 'projects/attachments/:projectid' => 'projects#attachments', :on => :collection
     get 'projects/attachments/create/:projectid' => 'projects#upload_attachments', :on => :collection
     post 'projects/attachments/create/:projectid' => 'attachments#create', :on => :collection
     # post 'projects/create' => 'projects#create', :on => :collection

     # Users Routes
     get 'projects/:projectid/users' => 'projects#users', :on => :collection
     get 'projects/:projectid/user/add' => 'projects#add_user', :on => :collection
     post 'projects/:projectid/user/add' => 'projects#create_user', :on => :collection
     get 'projects/:projectid/user/edit/:projectuserid' => 'projects#edit_user', :on => :collection
     post 'projects/:projectid/user/edit/:projectuserid' => 'projects#update_user', :on => :collection
     get 'projects/:projectid/user/delete/:projectuserid' => 'projects#delete_user', :on => :collection

     # Tasks Routes
     get 'projects/:projectid/tasks' => 'users#tasks', :on => :collection
     get 'projects/:projectid/task/add' => 'users#add_task', :on => :collection
     post 'projects/:projectid/task/add' => 'users#create_task', :on => :collection
     get 'projects/:projectid/task/edit/:task_id' => 'users#edit_task', :on => :collection
     post 'projects/:projectid/task/edit/:task_id' => 'users#update_task', :on => :collection
     get 'projects/:projectid/task/delete/:task_id' => 'users#delete_task', :on => :collection

     # Thread Routes
     get 'projects/:projectid/threads/:thread_id' => 'users#threads', :on => :collection
     get 'projects/:projectid/threads/:thread_id/message/edit/:message_id' => 'messages#edit', :on => :collection
     post 'projects/:projectid/threads/:thread_id/message/edit/:message_id' => 'messages#update', :on => :collection
     post 'projects/:projectid/threads/:thread_id' => 'messages#create', :on => :collection
     delete 'projects/:projectid/threads/:thread_id/message/:message_id' => 'messages#destroy', :on => :collection
     get 'projects/threads/:projectid' => 'projects#threads', :on => :collection
     get 'projects/thread/create/:projectid' => 'projects#add_thread', :on => :collection
     post 'projects/thread/create/:projectid' => 'project_threads#create', :on => :collection
     get 'projects/threads/:projectid/:thread_id/update' => 'projects#edit_thread', :on => :collection
     post 'projects/threads/:projectid/:thread_id/update' => 'project_threads#update', :on => :collection
     get 'projects/threads/:projectid/:thread_id/delete' => 'project_threads#destroy', :on => :collection
   end

   resources :admin do
     get 'logout', :on => :collection
     get 'login', :on => :collection
     get 'dashboard', :on => :collection
     get 'users' => 'admin#users', :on => :collection
     get 'users/projects/:userid' => 'admin#projects', :on => :collection
     get 'users/set_admin/:userid' => 'admin#set_admin', :on => :collection
     get 'users/unset_admin/:userid' => 'admin#unset_admin', :on => :collection
     post 'login' => 'admin#submit_login', :on => :collection
   end
   root 'users#index', as: 'home'

   namespace 'api' do
     namespace 'v1' do
       resources :users
       resources :projects do
         post 'user/:projectid/update' => 'projects#update_user', :on => :collection
       end
     end
   end
   # For details on the DSL a
 end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :projects, :dependent => :destroy
  has_many :tasks, :dependent => :destroy
  validates_uniqueness_of :email
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :userid, :fullname, presence: true, length: {minimum: 5}
  validates :password, presence: true, length: {minimum: 5}, on: :create


  has_many_attached :photos, :dependent => :destroy

end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
      class UsersController < ApplicationController
          skip_before_action :verify_authenticity_token
          def index
              users = User.order('created_at DESC')
              render json: {status: 'SUCCESS', 'message': 'Loaded Users', data: users},status: :ok
          end

          def show
              user = User.find(params[:id])
              render json: {status: 'SUCCESS', 'message': 'Loaded User', data: user},status: :ok
          end

          def create
              user = User.new(user_params)
              user[:userid] = SecureRandom.uuid
              if user.save
                  render json: {status: 'SUCCESS', 'message': 'User saved successfully', data: user},status: :ok
              else
                  render json: {status: 'ERROR', 'message': 'User Not Saved', data: user.errors},status: :unprocessable_entity
              end
          end

          def destroy
              begin
                  user = User.find(params[:id])
                  user.destroy
                  render json: {status: "SUCCESS", message: 'User Deleted Successully', data: user}, status: :ok
              rescue ActiveRecord::RecordNotFound => e
                  render json: {status: 'ERROR', message: 'User Not Deleted', data: e},status: :unprocessable_entity
              end
          end

          def update
              begin
                  user = User.find(params[:id])
                  user.update_attributes(user_params)
                  render json: {status: "SUCCESS", message: "User Updated Successfully", data: user}, status: :ok
              rescue ActiveRecord::RecordNotFound => e
                  render json: {status: "ERROR", message: "User Not Updated", data: e}, status: :ok
              end
          end

          private
              def user_params
                  params.permit(:fullname, :email, :password)
              end
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # layout :resolve_layout
    before_action :authorize_login, :only => [:login, :new]
    before_action :authorize_logout, :only => [:dashboard, :profile, :projects, :create_project, :edit_project, :show, :logout, :destroy, :threads, :add_thread]
    def index
        @user = User.new
    end

    def login
        @user = User.new
    end

    def submit_login
        # render plain: user_params.inspect
        @user = User.find_by_email(user_params[:email])
        if @user and @user.authenticate(user_params[:password])
            session[:logged_in] = true
            session[:email] = user_params[:email]
            session[:userid] = @user[:userid]
            session[:id] = @user[:id]
            # render plain: @user[:id]
            redirect_to dashboard_users_path, :flash => { :success => "You are logged in successfully as #{session[:email]}" }
        else
            # render plain: user_params
            if user_params[:email] == "" and user_params[:password] == ""
                flash[:error] = "Please Provide Email And Password"
            elsif user_params[:email] == ""
                flash[:error] = "Please Provide Email Address"
            elsif user_params[:password] == ""
                flash[:error] = "Please Provide Password"
            elsif @user == nil
                flash[:error] = "Incorrect Email Provided"
            elsif @user != nil and @user[:email] != ""
                flash[:error] = "Incorrect Password Provided"
            else
                flash[:error] = "Please Provide Correct Email And Password"
            end

            render 'login'
        end
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        @user[:userid] = SecureRandom.uuid
        # render plain: @user.inspect
        if (@user.save)
            redirect_to login_users_path, :flash => { :success => "You have successfully signed up. Please login now" }
        else
            render 'new'
        end
    end

    def dashboard
    end

    def profile
    end

    def update
        # render plain: user_params.inspect
        # @user = User.find_by_email(user_params)
    end

    def submit_profile
        @user = User.find_by_email(session[:email])
        if user_params[:email] == ""
            flash[:error] = "Please Provide A Valid Email Address"
            render 'profile'
        elsif user_params[:fullname] == ""
            flash[:error] = "Please Provide Your Full Name"
            render 'profile'
        else
            if (@user.update(user_params))
                flash[:success] = "Profile Updated Successfully"
                redirect_to profile_users_path
            else
                flash[:error] = "Profile Not Updated"
                render 'profile'
            end
        end
    end

    def projects
        if params[:query].present?
           sql_query = <<~SQL
      projects.title ILIKE :query
      OR projects.description ILIKE :query
    SQL
    @projects = Project.joins(:user).where(sql_query, query: "%#{params[:query]}%")
  else
        @pagy, @projects = pagy(@user.projects)
        end
        @bgs = ["#68428a","#a64791","#855635","#4c7e8a","#323e7a","#943469","#4d2227","#b05638","#4d0b47","#992b59","#1b5780","#046e6e","#254a22","#6d8748","#5d6344"]
        # render plain: @projects.inspect
    
    end

    def create_project
        @user = User.find_by_email(session[:email])
        # render plain: @user.inspect
    end

    def edit_project
        @project = Project.find_by(projectid: params[:projectid])
    end

    def show
        @active = "profile"
    end

    def destroy
        render plain: "Finally Destroyed"
        @user.destroy
        session[:logged_in] = session[:id] = session[:userid] = session[:email] = nil
        flash[:error] = "Account Deleted Successfully"
        redirect_to login_users_path
    end

    def threads
        @project = Project.find_by(projectid: params[:projectid])
        @project_thread = ProjectThread.find_by(project_thread_id: params[:thread_id])
        @message = Message.new
        @bgs = ["#68428a","#a64791","#855635","#4c7e8a","#323e7a","#943469","#4d2227","#b05638","#4d0b47","#992b59","#1b5780","#046e6e","#254a22","#6d8748","#5d6344"]
        # render plain: @project_thread.messages.inspect
    end

    def shared_projects
        @projects = ProjectUser.where("user_id = ?", session[:id])
        @pagy, @projects = pagy(@projects, items: 5)
        @bgs = ["#68428a","#a64791","#855635","#4c7e8a","#323e7a","#943469","#4d2227","#b05638","#4d0b47","#992b59","#1b5780","#046e6e","#254a22","#6d8748","#5d6344"]
        # render plain: @projects[0].project.inspect
    end

    def logout
        session[:logged_in] = session[:id] = session[:userid] = session[:email] = nil
        flash[:error] = "You have logged out successfuly! Please login again"
        redirect_to login_users_path
    end

    def tasks
        @project = Project.find_by(projectid: params[:projectid])
    end

    def add_task
        @task = Task.new
        @project = Project.find_by(projectid: params[:projectid])
    end

    def create_task
        @task = Task.new(task_params)
        @project = Project.find_by(projectid: params[:projectid])
        @task.project_id = @project[:id]
        @task.user_id = @project[:user_id]
        @task.task_id = SecureRandom.uuid
        
        if (@task.save)
            flash[:success] = "Task created Successfully"
            redirect_to projects_users_path + "/#{params[:projectid]}/tasks"
        else
            flash[:error] = "You have some errors there"
            render 'add_task'
        end
    end

    def edit_task
        @task = Task.find_by(task_id: params[:task_id])
        @project = Project.find_by(projectid: params[:projectid])
    end

    def update_task
        @task = Task.find_by(task_id: params[:task_id])
        if @task.update(task_params)
            flash[:success] = "Task updated Successfully"
            redirect_to projects_users_path + "/#{params[:projectid]}/tasks"
        else
            flash[:error] = "You have some errors there"
            render 'edit_task'
        end
    end

    def delete_task
        @task = Task.find_by(task_id: params[:task_id])
        @task.destroy
        flash[:error] = "Task deleted Successfully"
        redirect_to projects_users_path + "/#{params[:projectid]}/tasks"
    end

    private
        def user_params
            params.require(:user).permit(:fullname, :email, :password, photos: [])
        end

        def task_params
            params.require(:task).permit(:title)
        end

        def resolve_layout
            case action_name
            when "threads"
                "index_layout"
            else
                "application"
            end
        end

end
# http://localhost:3000/users/projects/c8cba1f2-43ca-4229-acc3-a8e305a961ed/users

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create_project.html.erb
<div class="change-padding" style="margin-top:30px">
    <div class="row">
        <%= render "links/links", :locals => {:active => 'create_project'} %>
        <div class="col-md-9 bg-white right-part">
            <h3 class="">Create A Project</h3>
            <% flash.each do |type, msg| %>
                <% if type == 'success' %>
                    <div class="alert alert-success"><%= msg %></div>
                <% elsif type == 'error' %>
                    <div class="alert alert-danger"><%= msg %></div>
                <% else %>
                    <div class="alert alert-info"><%= msg %></div>
                <% end %>
            <% end %>
            <%= simple_form_for :project, url: projects_create_users_path, html: {class: 'login-form'} do |f| %>
                <%= f.text_field :title, class: 'form-control', placeholder: 'Enter Project Title' %>
                    <%# if @project != nil and @project.errors.any? and @project.errors.to_h[:title].to_s != "" %>
                        <!-- <div class="alert alert-danger"><#%= "Title " + @project.errors.to_h[:title].to_s %></div> -->
                    <%# end %>
                <%= f.text_area :description, class: 'form-control', placeholder: 'Enter Project Description' %>
                    <%# #if @project != nil and @project.errors.any? and @project.errors.to_h[:description].to_s != "" %>
                    <!--     <div class="alert alert-danger"><%#= "Description " + @project.errors.to_h[:description].to_s %></div> -->
                    <%# end %>
<div class="field">
            <%= f.label :body %>
            <%= f.rich_text_area :body %>
        </div>
<div class="field">
            <%= f.label :body %>
            <%= f.rich_text_area :body %>
        </div>
 <div class="container mb-2">
                            <%= f.input :photos, as: :file, input_html: { multiple: true }%>

                        </div>


        <%#= f.input :photos, as: :file, input_html: { multiple: true } %>
                <%= f.submit "Submit Project", class: 'form-submit'%>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<section class="hero">
    <div class="img-container">
        <%#= image_tag '2128317.jpg', :class => 'rounded' %>
    </div>
    <div class="title">Project Management Web App</div>
</section>

app/views/users/new.html.erb
<section class="login turn-up">
    <div class="user-pic"></div>
    <div class="form-header">User Sign Up</div>
    <% flash.each do |type, msg| %>
        <div class="alert alert-danger"><%= msg %></div>
    <% end %>
    <%= form_for :user, url: users_path, html: {class: 'login-form'} do |f| %>
        <%= f.email_field :email, class: 'form-control', placeholder: 'Enter Your Email Address' %>
        <%# if @user != nil and @user.errors.any? and @user.errors.to_h[:email].to_s != "" %>
            <div class="alert alert-danger"><%#= "Email " + @user.errors.to_h[:email].to_s %></div>
        <%# end %>
        <%= f.text_field :fullname, class: 'form-control', placeholder: 'Enter Your Full Name' %>
        <%# if @user != nil and @user.errors.any? and @user.errors.to_h[:fullname].to_s != "" %>
            <div class="alert alert-danger"><%#= "Full Name " + @user.errors.to_h[:fullname].to_s %></div>
        <%# end %>
        <%= f.password_field :password, class: 'form-control', placeholder: 'Enter Your Password' %>
        <%# if @user != nil and @user.errors.any? and @user.errors.to_h[:password].to_s != "" %>
            <div class="alert alert-danger"><%#= "Password " + @user.errors.to_h[:password].to_s %></div>
        <%# end %>
        
        <%= f.submit "Sign Up", class: 'form-submit', placeholder: 'Enter Your Password' %>
    <% end %>
</section>

app/views/users/projects.html.erb
        <div class="change-padding" style="margin-top:30px">
            <div class="row">
                <%= render "links/links", :locals => {:active => 'projects'} %>
                <% if false %>
                <div class="col-md-9 bg-white right-part">
                    <h3>Your Project List</h3>
                    <% flash.each do |type, msg| %>
                        <% if type == 'success' %>
                            <div class="alert alert-success"><%= msg %></div>
                        <% elsif type == 'error' %>
                            <div class="alert alert-danger"><%= msg %></div>
                        <% else %>
                            <div class="alert alert-info"><%= msg %></div>
                        <% end %>
                    <% end %>
                    <br>
                    <table class="table">
                        <thead>
                            <tr>
                            <th scope="col">#</th>
                            <th scope="col">Title</th>
                            <th scope="col">Description</th>
                            <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% count = 0 %>
                            <% @projects.each do |project| %>
                            <tr>
                            <th scope="row"><%= count += 1 %></th>
                            <td><%= project.title %></td>
                            <td><%= project.description %></td>
                            <td>
                                <%= link_to "View", users_path + "/projects/view/#{project.projectid}", :class => 'btn btn-sm btn-primary' %>
                                <%= link_to "Edit", users_path + "/projects/edit/#{project.projectid}", :class => 'btn btn-sm btn-secondary' %>
                                <%= link_to "Delete", users_path + "/projects/delete/#{project.projectid}", data: {confirm: "Are you sure you want to delete this project?"}, :class => 'btn btn-sm btn-danger' %>
                            </td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <%= pagy_nav(@pagy).html_safe %>
                </div>
                <% end %>
                
                <div class="col-md-9 no-bg">


<div class="container search-bar-container mt-1">
    <%= form_with url: projects_users_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a project"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
</div>
                    
                    <h5 class="mt-2">Your Projects</h5>
                    <% flash.each do |type, msg| %>
                        <% if type == 'success' %>
                            <div class="alert alert-success"><%= msg %></div>
                        <% elsif type == 'error' %>
                            <div class="alert alert-danger"><%= msg %></div>
                        <% else %>
                            <div class="alert alert-info"><%= msg %></div>
                        <% end %>
                    <% end %>



                    <div class="row">
                        <% @projects.order(created_at: :desc).each do |project| %>
                        <div class="col-md-6 add-card">
                            <div class="three-circles" id="<%= project.projectid %>">
                                <div class="circle"></div>
                                <div class="circle"></div>
                                <div class="circle"></div>
                            </div>
                            <div class="kite" id="<%= project.projectid %>"></div>
                            <div class="action-links" id="<%= project.projectid %>">
                                <%= link_to users_path + "/projects/thread/create/#{project.projectid}", :class => 'action-link' do %>
                                    <i class="fa fa-plus"></i>&nbsp;New Thread
                                <% end %>
                                <%= link_to users_path + "/projects/threads/#{project.projectid}", :class => 'action-link' do %>
                                    <i class="fa fa-list-alt"></i>&nbsp;Threads
                                <% end %>
                            </div>
                            <div class="first-letter" style="background-color:<%= @bgs.sample %>"><%= project.title[0] %></div>
                            <p class="text-center project-text"><%= project.title %></p>
                            <p class="text-center project-text"><%#= project.description %></p>
                            <div class="text-center">
                                <%= link_to users_path + "/projects/#{project.projectid}/tasks", :class => 'btn btn-sm btn-secondary all-center', :style => 'background-color: #5d6344;border: 1px solid #5d6344;', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Tasks Link" do %>
                                    <i class="fa fa-tasks"></i>
                                <% end %>
                                <%= link_to users_path + "/projects/#{project.projectid}/users", :class => 'btn btn-sm btn-secondary all-center', :style => 'background-color:#323e7a;border: 1px solid #323e7a;', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Users Link" do %>
                                    <i class="fa fa-user"></i>
                                <% end %>
                                <%= link_to users_path + "/projects/threads/#{project.projectid}", :class => 'btn btn-sm btn-secondary all-center', :style => 'background-color:#4d2227;border: 1px solid #4d2227;', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Thread Link" do %>
                                    <i class="fa fa-thermometer-three-quarters"></i>
                                <% end %>
                                <%= link_to users_path + "/projects/view/#{project.projectid}", :class => 'btn btn-sm btn-primary all-center', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "View Project Details" do %>
                                    <i class="fa fa-eye"></i>
                                <% end %>
                                <%= link_to users_path + "/projects/edit/#{project.projectid}", :class => 'btn btn-sm btn-secondary all-center', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Edit Project Details"  do %>
                                    <i class="fa fa-edit"></i>
                                <% end %>
                                <%= link_to users_path + "/projects/delete/#{project.projectid}", data: {confirm: "Are you sure you want to delete this project?"}, :class => 'btn btn-sm btn-danger all-center', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Delete Project"  do %>
                                    <i class="fa fa-trash"></i>
                                <% end %>
                            </div>
                        </div>
                        <% end %>
                        <%# pagy_nav(@pagy).html_safe %>
                </div>
            </div>
        </div>

app/views/users/shared_projects.html.erb
<div class="change-padding" style="margin-top:30px">
    <div class="row">
        <%= render "links/links", :locals => {:active => 'projects'} %>
        <% if false %>
        <div class="col-md-9 bg-white right-part">
            <h3>Your Project List</h3>
            <% flash.each do |type, msg| %>
                <% if type == 'success' %>
                    <div class="alert alert-success"><%= msg %></div>
                <% elsif type == 'error' %>
                    <div class="alert alert-danger"><%= msg %></div>
                <% else %>
                    <div class="alert alert-info"><%= msg %></div>
                <% end %>
            <% end %>
            <br>
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% count = 0 %>
                    <% @projects.each do |project| %>
                    <tr>
                        <td scope="row"><%= count += 1 %></td>
                        <td><%= project.project.title %></td>
                        <td><%= project.project.description %></td>
                        <td>
                            <%= link_to "View", users_path + "/projects/view/#{project.project.projectid}", :class => 'btn btn-sm btn-primary' %>
                            <%= link_to "Edit", users_path + "/projects/edit/#{project.project.projectid}", :class => 'btn btn-sm btn-secondary' %>
                            <%= link_to "Delete", users_path + "/projects/delete/#{project.project.projectid}", data: {confirm: "Are you sure you want to delete this project?"}, :class => 'btn btn-sm btn-danger' %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <%= pagy_nav(@pagy).html_safe %>
        </div>
        <% end %>
        
        <div class="col-md-9 no-bg">
            <h3>Projects Shared With You</h3>
            <% flash.each do |type, msg| %>
                <% if type == 'success' %>
                    <div class="alert alert-success"><%= msg %></div>
                <% elsif type == 'error' %>
                    <div class="alert alert-danger"><%= msg %></div>
                <% else %>
                    <div class="alert alert-info"><%= msg %></div>
                <% end %>
            <% end %>
            <div class="row">
                <% @projects.each do |project| %>
                <div class="col-md-6 add-card">
                    <div class="three-circles" id="<%= project.project.projectid %>">
                        <div class="circle"></div>
                        <div class="circle"></div>
                        <div class="circle"></div>
                    </div>
                    <div class="kite" id="<%= project.project.projectid %>"></div>
                    <div class="action-links" id="<%= project.project.projectid %>">
                        <%= link_to users_path + "/projects/thread/create/#{project.project.projectid}", :class => 'action-link' do %>
                            <i class="fa fa-plus"></i>&nbsp;New Thread
                        <% end %>
                        <%= link_to users_path + "/projects/threads/#{project.project.projectid}", :class => 'action-link' do %>
                            <i class="fa fa-list-alt"></i>&nbsp;Threads
                        <% end %>
                    </div>
                    <div class="first-letter" style="background-color:<%= @bgs.sample %>"><%= project.project.title[0] %></div>
                    <p class="text-center project-text"><%= project.project.title %></p>
                    <p class="text-center project-text"><%#= project.project.description %></p>
                    <div class="text-center">
                        <%= link_to users_path + "/projects/#{project.project.projectid}/tasks", :class => 'btn btn-sm btn-secondary all-center', :style => 'background-color: #5d6344;border: 1px solid #5d6344;', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Tasks Link" do %>
                            <i class="fa fa-tasks"></i>
                        <% end %>
                        <%#= link_to users_path + "/projects/#{project.project.projectid}/users", :class => 'btn btn-sm btn-secondary all-center', :style => 'background-color:#323e7a;border: 1px solid #323e7a;', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Users Link" do %>
                          <!--   <i class="fa fa-user"></i> -->
                        <%# end %>
                        <%= link_to users_path + "/projects/threads/#{project.project.projectid}", :class => 'btn btn-sm btn-secondary all-center', :style => 'background-color:#4d2227;border: 1px solid #4d2227;', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Thread Link" do %>
                            <i class="fa fa-thermometer-three-quarters"></i>
                        <% end %>
                        <%= link_to users_path + "/projects/view/#{project.project.projectid}", :class => 'btn btn-sm btn-primary all-center', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "View Project Details" do %>
                            <i class="fa fa-eye"></i>
                        <% end %>
                        <%#= link_to users_path + "/projects/edit/#{project.project.projectid}", :class => 'btn btn-sm btn-secondary all-center', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Edit Project Details"  do %>
                           <!--  <i class="fa fa-edit"></i> -->
                        <%# end %>
                        <%#= link_to users_path + "/projects/delete/#{project.project.projectid}", data: {confirm: "Are you sure you want to delete this project?"}, :class => 'btn btn-sm btn-danger all-center', "data-toggle" => "tooltip", "data-placement" => "top", "title" => "Delete Project"  do %>
                            <!-- <i class="fa fa-trash"></i> -->
                        <%# end %>
                    </div>
                </div>
                <% end %>
                <%# pagy_nav(@pagy).html_safe %>
        </div>
    </div>
</div>