config/routes.rb
Rails.application.routes.draw do
  resources :messages
   resources :project_threads
   resources :attachments
   resources :users do
     resources :projects
     get 'logout', :on => :collection
     get 'login', :on => :collection
     post 'login' => 'users#submit_login', :on => :collection
     get 'dashboard', :on => :collection
     get 'profile', :on => :collection
     patch 'profile' => 'users#submit_profile', :on => :collection
     get 'projects', :on => :collection
     get 'projects/shared' => "users#shared_projects", :on => :collection
     get 'projects/create' => 'users#create_project', :on => :collection
     post 'projects/create' => 'projects#create', :on => :collection
     get 'projects/view/:projectid' => 'projects#show', :on => :collection
     get 'projects/edit/:projectid' => 'users#edit_project', :on => :collection
     post 'projects/edit/:projectid' => 'projects#update', :on => :collection
     get 'projects/delete/:projectid' => 'projects#destroy', :on => :collection
     get 'projects/:projectid/attachments/delete/:id' => 'projects#delete_attachment', :on => :collection
     get 'projects/attachments/:projectid' => 'projects#attachments', :on => :collection
     get 'projects/attachments/create/:projectid' => 'projects#upload_attachments', :on => :collection
     post 'projects/attachments/create/:projectid' => 'attachments#create', :on => :collection
     # post 'projects/create' => 'projects#create', :on => :collection

     # Users Routes
     get 'projects/:projectid/users' => 'projects#users', :on => :collection
     get 'projects/:projectid/user/add' => 'projects#add_user', :on => :collection
     post 'projects/:projectid/user/add' => 'projects#create_user', :on => :collection
     get 'projects/:projectid/user/edit/:projectuserid' => 'projects#edit_user', :on => :collection
     post 'projects/:projectid/user/edit/:projectuserid' => 'projects#update_user', :on => :collection
     get 'projects/:projectid/user/delete/:projectuserid' => 'projects#delete_user', :on => :collection

     # Tasks Routes
     get 'projects/:projectid/tasks' => 'users#tasks', :on => :collection
     get 'projects/:projectid/task/add' => 'users#add_task', :on => :collection
     post 'projects/:projectid/task/add' => 'users#create_task', :on => :collection
     get 'projects/:projectid/task/edit/:task_id' => 'users#edit_task', :on => :collection
     post 'projects/:projectid/task/edit/:task_id' => 'users#update_task', :on => :collection
     get 'projects/:projectid/task/delete/:task_id' => 'users#delete_task', :on => :collection

     # Thread Routes
     get 'projects/:projectid/threads/:thread_id' => 'users#threads', :on => :collection
     get 'projects/:projectid/threads/:thread_id/message/edit/:message_id' => 'messages#edit', :on => :collection
     post 'projects/:projectid/threads/:thread_id/message/edit/:message_id' => 'messages#update', :on => :collection
     post 'projects/:projectid/threads/:thread_id' => 'messages#create', :on => :collection
     delete 'projects/:projectid/threads/:thread_id/message/:message_id' => 'messages#destroy', :on => :collection
     get 'projects/threads/:projectid' => 'projects#threads', :on => :collection
     get 'projects/thread/create/:projectid' => 'projects#add_thread', :on => :collection
     post 'projects/thread/create/:projectid' => 'project_threads#create', :on => :collection
     get 'projects/threads/:projectid/:thread_id/update' => 'projects#edit_thread', :on => :collection
     post 'projects/threads/:projectid/:thread_id/update' => 'project_threads#update', :on => :collection
     get 'projects/threads/:projectid/:thread_id/delete' => 'project_threads#destroy', :on => :collection
   end

   resources :admin do
     get 'logout', :on => :collection
     get 'login', :on => :collection
     get 'dashboard', :on => :collection
     get 'users' => 'admin#users', :on => :collection
     get 'users/projects/:userid' => 'admin#projects', :on => :collection
     get 'users/set_admin/:userid' => 'admin#set_admin', :on => :collection
     get 'users/unset_admin/:userid' => 'admin#unset_admin', :on => :collection
     post 'login' => 'admin#submit_login', :on => :collection
   end
   root 'users#index', as: 'home'

   namespace 'api' do
     namespace 'v1' do
       resources :users
       resources :projects do
         post 'user/:projectid/update' => 'projects#update_user', :on => :collection
       end
     end
   end
   # For details on the DSL a
 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tryy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">


    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_tag src="https://code.jquery.com/jquery-3.4.1.min.js" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class="nav p-2 bg-light-dark text-white bg-dark flex fixed-top">
  <div class="nav-item m-1">
    <% if logged_in? %>
         | <%= link_to "Profile", profile_users_path %> |
          <%#= link_to "Logout", logout_users_path %>
    <% else %>
  </div>
  <div class="nav-item m-1">
    <%= link_to "SignIn", login_users_path %>
          <%= link_to "SignUp", new_user_path %>
        <% end %>
  </div>

</div>

    <%= yield %>
<%= javascript_tag src="https://code.jquery.com/jquery-3.4.1.min.js" %>
  </body>
</html>

app/views/layouts/index_layout.html.erb
<!DOCTYPE html>
<html lang="en" class="no-grey-bg">
<head>
    <title>Ebuddy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" %>
    <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
</head>
<body class="no-grey-bg">
    <%= yield %>
    <%= javascript_tag src="https://code.jquery.com/jquery-3.4.1.min.js" %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</body>
</html>